// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddxexqdujdmqiwdmvsoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkeGV4cWR1amRtcWl3ZG12c29hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMzA1MzYsImV4cCI6MjA1NjcwNjUzNn0.KI9JVeq0I_LkE71BOPfQWXqiAxNJ4TNiLVBIrvtQ4uo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);